In [4]:
import numpy as np
import pandas as pd

from sqlalchemy import create_engine

In [5]:
df=pd.read_csv(r"C:\Users\dell\Desktop\New folder\HR analyst.csv",encoding_errors='ignore')

In [6]:
df.shape

(10000, 19)

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 19 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Employee_ID                  10000 non-null  int64
 1   Department                   10000 non-null  str
 2   Gender                       10000 non-null  str
 3   Age                          10000 non-null  int64
 4   Job_Title                    10000 non-null  str
 5   Years_At_Company             10000 non-null  int64
 6   Education_Level              10000 non-null  str
 7   Performance_Score            10000 non-null  int64
 8   Monthly_Salary               10000 non-null  int64
 9   Work_Hours_Per_Week          10000 non-null  int64
 10  Projects_Handled             10000 non-null  int64
 11  Overtime_Hours               10000 non-null  int64
 12  Sick_Days                    10000 non-null  int64
 13  Remote_Work_Frequency        10000 non-null  int64
 14  Team_Size                    10000 non-null  int64
 15  Training_Hours               10000 non-null  int64
 16  Promotions                   10000 non-null  int64
 17  Employee_Satisfaction_Score  10000 non-null  float64
 18  Resigned                     10000 non-null  bool
dtypes: bool(1), float64(1), int64(13), str(4)
memory usage: 1.4 MB

In [8]:
df.head(5)

,Employee_ID,Department,Gender,Age,Job_Title,Years_At_Company,Education_Level,Performance_Score,Monthly_Salary,Work_Hours_Per_Week,Projects_Handled,Overtime_Hours,Sick_Days,Remote_Work_Frequency,Team_Size,Training_Hours,Promotions,Employee_Satisfaction_Score,Resigned
0,1,IT,Male,55,Specialist,2,High School,5,6750,33,32,22,2,0,14,66,0,2.63,False
1,2,Finance,Male,29,Developer,0,High School,5,7500,34,34,13,14,100,12,61,2,1.72,False
2,3,Finance,Male,55,Specialist,8,High School,3,5850,37,27,6,3,50,10,1,0,3.17,False
3,4,Customer Support,Female,48,Analyst,7,Bachelor,2,4800,52,10,28,12,100,10,0,1,1.86,False
4,5,Engineering,Female,36,Analyst,3,Bachelor,2,4800,38,11,29,13,100,15,9,1,1.25,False

In [9]:
df.describe()

,Employee_ID,Age,Years_At_Company,Performance_Score,Monthly_Salary,Work_Hours_Per_Week,Projects_Handled,Overtime_Hours,Sick_Days,Remote_Work_Frequency,Team_Size,Training_Hours,Promotions,Employee_Satisfaction_Score
count,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,5000.50000,40.918000,4.522600,2.997900,6404.990000,45.095200,24.329200,14.528800,7.004300,49.955000,9.979300,49.025400,1.000300,2.993591
std,2886.89568,11.198465,2.844134,1.418131,1374.253782,8.932341,14.361088,8.659623,4.349296,35.330551,5.472026,28.912979,0.814473,1.145357
min,1.00000,22.000000,0.000000,1.000000,3850.000000,30.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000
25%,2500.75000,31.000000,2.000000,2.000000,5250.000000,37.000000,12.000000,7.000000,3.000000,25.000000,5.000000,24.000000,0.000000,2.010000
50%,5000.50000,41.000000,5.000000,3.000000,6500.000000,45.000000,24.000000,15.000000,7.000000,50.000000,10.000000,49.000000,1.000000,2.980000
75%,7500.25000,51.000000,7.000000,4.000000,7500.000000,53.000000,37.000000,22.000000,11.000000,75.000000,15.000000,74.000000,2.000000,3.990000
max,10000.00000,60.000000,10.000000,5.000000,9000.000000,60.000000,49.000000,29.000000,14.000000,100.000000,19.000000,99.000000,2.000000,5.000000

In [10]:
df.isnull().sum()

Employee_ID                    0
Department                     0
Gender                         0
Age                            0
Job_Title                      0
Years_At_Company               0
Education_Level                0
Performance_Score              0
Monthly_Salary                 0
Work_Hours_Per_Week            0
Projects_Handled               0
Overtime_Hours                 0
Sick_Days                      0
Remote_Work_Frequency          0
Team_Size                      0
Training_Hours                 0
Promotions                     0
Employee_Satisfaction_Score    0
Resigned                       0
dtype: int64

In [11]:
df.columns

Index(['Employee_ID', 'Department', 'Gender', 'Age', 'Job_Title',
       'Years_At_Company', 'Education_Level', 'Performance_Score',
       'Monthly_Salary', 'Work_Hours_Per_Week', 'Projects_Handled',
       'Overtime_Hours', 'Sick_Days', 'Remote_Work_Frequency', 'Team_Size',
       'Training_Hours', 'Promotions', 'Employee_Satisfaction_Score',
       'Resigned'],
      dtype='str')

In [12]:

df.duplicated().sum()

np.int64(0)

In [13]:
df.tail(5)

,Employee_ID,Department,Gender,Age,Job_Title,Years_At_Company,Education_Level,Performance_Score,Monthly_Salary,Work_Hours_Per_Week,Projects_Handled,Overtime_Hours,Sick_Days,Remote_Work_Frequency,Team_Size,Training_Hours,Promotions,Employee_Satisfaction_Score,Resigned
9995,9996,IT,Female,22,Developer,5,High School,5,7500,60,2,12,11,25,2,99,1,2.71,False
9996,9997,HR,Female,35,Specialist,8,Bachelor,5,6750,51,35,15,1,0,4,51,1,1.71,False
9997,9998,IT,Male,26,Analyst,0,Bachelor,2,4800,40,23,10,11,100,12,13,1,4.42,False
9998,9999,Finance,Male,38,Analyst,5,Bachelor,5,6000,32,31,22,6,50,2,55,0,1.11,False
9999,10000,Customer Support,Male,33,Developer,3,High School,5,7500,54,20,0,5,0,4,57,0,3.59,False

In [14]:
df.dtypes

Employee_ID                      int64
Department                         str
Gender                             str
Age                              int64
Job_Title                          str
Years_At_Company                 int64
Education_Level                    str
Performance_Score                int64
Monthly_Salary                   int64
Work_Hours_Per_Week              int64
Projects_Handled                 int64
Overtime_Hours                   int64
Sick_Days                        int64
Remote_Work_Frequency            int64
Team_Size                        int64
Training_Hours                   int64
Promotions                       int64
Employee_Satisfaction_Score    float64
Resigned                          bool
dtype: object

In [15]:
#salary analysis by department & Gender
df.groupby(['Department','Gender'])['Monthly_Salary'].mean()

Department        Gender
Customer Support  Female    6386.918605
                  Male      6342.943201
                  Other     6105.263158
Engineering       Female    6484.629295
                  Male      6417.314488
                  Other     6206.000000
Finance           Female    6405.833333
                  Male      6432.887189
                  Other     6673.958333
HR                Female    6355.963303
                  Male      6396.408318
                  Other     6470.175439
IT                Female    6487.238095
                  Male      6521.988528
                  Other     6504.545455
Legal             Female    6332.149362
                  Male      6453.830645
                  Other     6354.838710
Marketing         Female    6334.386282
                  Male      6380.912477
                  Other     6856.250000
Operations        Female    6494.433781
                  Male      6310.126582
                  Other     6215.476190
Sales             Female    6436.381710
                  Male      6301.369863
                  Other     6482.000000
Name: Monthly_Salary, dtype: float64

In [16]:
df['Employee_ID'].unique()

array([    1,     2,     3, ...,  9998,  9999, 10000], shape=(10000,))

In [17]:
df['Employee_ID'].value_counts()

Employee_ID
1        1
2        1
3        1
4        1
5        1
        ..
9996     1
9997     1
9998     1
9999     1
10000    1
Name: count, Length: 10000, dtype: int64

In [18]:
df.groupby('Department')['Monthly_Salary'].mean()

Department
Customer Support    6354.977974
Engineering         6445.236014
Finance             6430.153015
HR                  6380.636605
IT                  6504.578755
Legal               6388.894052
Marketing           6374.933687
Operations          6392.607527
Sales               6373.684211
Name: Monthly_Salary, dtype: float64

In [19]:
df.to_csv('HR_analyst',index=False)

In [20]:
df.head()

,Employee_ID,Department,Gender,Age,Job_Title,Years_At_Company,Education_Level,Performance_Score,Monthly_Salary,Work_Hours_Per_Week,Projects_Handled,Overtime_Hours,Sick_Days,Remote_Work_Frequency,Team_Size,Training_Hours,Promotions,Employee_Satisfaction_Score,Resigned
0,1,IT,Male,55,Specialist,2,High School,5,6750,33,32,22,2,0,14,66,0,2.63,False
1,2,Finance,Male,29,Developer,0,High School,5,7500,34,34,13,14,100,12,61,2,1.72,False
2,3,Finance,Male,55,Specialist,8,High School,3,5850,37,27,6,3,50,10,1,0,3.17,False
3,4,Customer Support,Female,48,Analyst,7,Bachelor,2,4800,52,10,28,12,100,10,0,1,1.86,False
4,5,Engineering,Female,36,Analyst,3,Bachelor,2,4800,38,11,29,13,100,15,9,1,1.25,False

In [21]:
import pandas as pd
from sqlalchemy import create_engine

In [22]:
print("Running new code")
try:
    engine = create_engine("postgresql://postgres:1234@localhost:5432/hr_analyst")

    with engine.connect() as conn:
        print("Connection succeeded to PostgreSQL")

except Exception as e:
    print("Unable to connect")
    print("Error:", e)

Running new code
Connection succeeded to PostgreSQL

In [23]:
df.to_sql(
    "hr_analyst",
    con=engine,
    if_exists="replace",
    index=False
)

print("Table created")

Table created

In [24]:
from sqlalchemy import text

with engine.connect() as conn:
    result = conn.execute(text("SELECT table_name FROM information_schema.tables WHERE table_schema='public';"))
    print(result.fetchall())

[('employee_data',), ('hr_analyst',)]

In [27]:
from sqlalchemy import text

with engine.connect() as conn:
    result = conn.execute(text("SELECT * FROM hr_analyst LIMIT 5"))
    for row in result:
        print(row)

(1, 'IT', 'Male', 55, 'Specialist', 2, 'High School', 5, 6750, 33, 32, 22, 2, 0, 14, 66, 0, 2.63, False)
(2, 'Finance', 'Male', 29, 'Developer', 0, 'High School', 5, 7500, 34, 34, 13, 14, 100, 12, 61, 2, 1.72, False)
(3, 'Finance', 'Male', 55, 'Specialist', 8, 'High School', 3, 5850, 37, 27, 6, 3, 50, 10, 1, 0, 3.17, False)
(4, 'Customer Support', 'Female', 48, 'Analyst', 7, 'Bachelor', 2, 4800, 52, 10, 28, 12, 100, 10, 0, 1, 1.86, False)
(5, 'Engineering', 'Female', 36, 'Analyst', 3, 'Bachelor', 2, 4800, 38, 11, 29, 13, 100, 15, 9, 1, 1.25, False)